[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "bag3d-party-walls"
version = "2024.1004"
description = "Workflow for calculating the party walls in the 3D BAG."
readme = "README.md"
requires-python = ">=3.11"
authors = [
    { name = "Balázs Dukai", email = "balazs.dukai@3dgi.nl" },
    { name = "Ravi Peters", email = "ravi.peters@3dgi.nl" },
    { name = "Gina Stavropoulou", email = "G.Stavropoulou@tudelft.nl" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: GIS",
    "License :: OSI Approved :: Apache Software License"
]
urls = { github = "https://github.com/3DBAG/3dbag-pipeline" }
dependencies = [
    "dagster~=1.9.4",
    "dagster-postgres~=0.25.4",
    "numpy~=1.24.4",
    "pandas~=2.1.0",
    "shapely~=2.0.1",
    "urban-morphology-3d",
    "bag3d-common",
]

[project.optional-dependencies] 
dev = [
    "coverage~=7.6.8",
    "pytest~=8.3.4",
    "pytest-dotenv~=0.5.2",
]

[tool.ruff]
line-length = 88

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = false

[tool.uv.sources]
urban-morphology-3d = { git = "https://github.com/3DGI/urban-morphology-3d.git", rev = "onlysharedwalls" }
bag3d-common = { path = "../common", editable = true}