from dataclasses import dataclass
from typing import Optional


@dataclass
class Attributes:
    b3_bag_bag_overlap: float
    b3_dak_type: str
    b3_extrusie: int
    b3_h_dak_50p: float
    b3_h_dak_70p: float
    b3_h_dak_max: float
    b3_h_dak_min: float
    b3_h_maaiveld: float
    b3_is_glas_dak: bool
    b3_kas_warenhuis: bool
    b3_mutatie_AHN3_AHN4: bool
    b3_mutatie_AHN4_AHN5: bool
    b3_n_vlakken: int
    b3_nodata_fractie_AHN3: float
    b3_nodata_fractie_AHN4: float
    b3_nodata_fractie_AHN5: float
    b3_nodata_radius_AHN3: float
    b3_nodata_radius_AHN4: float
    b3_nodata_radius_AHN5: float
    b3_puntdichtheid_AHN3: float
    b3_puntdichtheid_AHN4: float
    b3_puntdichtheid_AHN5: float
    b3_pw_bron: str
    b3_pw_datum: int
    b3_pw_onvoldoende: bool
    b3_pw_selectie_reden: str
    b3_rmse_lod12: float
    b3_rmse_lod13: float
    b3_rmse_lod22: float
    b3_succes: bool
    b3_t_run: int
    b3_val3dity_lod12: str
    b3_val3dity_lod13: str
    b3_val3dity_lod22: str
    b3_volume_lod12: float
    b3_volume_lod13: float
    b3_volume_lod22: float
    begingeldigheid: str
    documentdatum: str
    documentnummer: str
    eindgeldigheid: Optional[str]
    eindregistratie: Optional[str]
    fid: int
    geconstateerd: bool
    identificatie: str
    oorspronkelijkbouwjaar: int
    rf_force_lod11: bool
    status: str
    tijdstipeindregistratielv: str
    tijdstipinactief: str
    tijdstipinactieflv: str
    tijdstipnietbaglv: str
    tijdstipregistratie: str
    tijdstipregistratielv: str
    voorkomenidentificatie: str
    b3_opp_grond: float
    b3_opp_dak_plat: float
    b3_opp_dak_schuin: float
    b3_opp_scheidingsmuur: float
    b3_opp_buitenmuur: float
