[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "bag3d-floors-estimation"
version = "2024.1001"
description = "Workflow for predicting the number of floors, based on Ellie Roy's thesis."
readme = "README.md"
requires-python = ">=3.11"
authors = [
    { name = "Gina Stavropoulou", email = "G.Stavropoulou@tudelft.nl" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: GIS",
    "License :: OSI Approved :: Apache Software License"
]
urls = { github = "https://github.com/3DBAG/3dbag-pipeline" }
dependencies = [
    "bag3d-common @ git+ssh://git@github.com/3DBAG/3dbag-pipeline.git#egg=bag3d-common&subdirectory=packages/common",
    "sklearn-pandas",
    "scikit-learn",
    "pandas",
    "dagster",
    "dagster-postgres",
]
optional-dependencies = { dev = ["pytest", "bumpver", "tox", "pytest-postgresql"] }
