services:
  postgres:
    image: $IMAGE_NAME
    command: ["-c", "shared_buffers=8GB", "-c", "max_connections=50", "-c", "work_mem=30MB"] 
    platform: linux/amd64
    container_name: $CONTAINER_NAME
    ports:
      - "5560:5432"
    volumes:
      - $PATH_TO_TEST_DATA:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    restart: always