[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "bag3d-pipeline"
version = "2023.1001"
dependencies = [
    "dagster-webserver"
]
optional-dependencies = { dev = ["bumpver", "tox"] }
