[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "bag3d-common"
version = "2024.1003"
description = "Resources, functions and type definitions that are used by the 3D BAG packages that define the data processing workflows."
readme = "README.md"
requires-python = ">=3.8"
authors = [
    { name = "Balázs Dukai", email = "balazs.dukai@3dgi.nl" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: GIS",
    "License :: OSI Approved :: Apache Software License"
]
urls = { github = "https://github.com/3DBAG/3dbag-pipeline" }
dependencies = [
    "dagster",
    "dagster-shell",
    "docker",
    "pgutils @ git+https://github.com/balazsdukai/pgutils.git@2024.1013#egg=pgutils",
    "psycopg[binary]",
    "requests",
]

[project.optional-dependencies]
dev = [
    "bumpver",
    "tox",
    "pytest",
    "pytest-dotenv",
    "coverage"
]
docs = [
    "mkdocs",
    "mkdocstrings[python]",
    "mkdocs-gen-files",
    "mkdocs-literate-nav",
    "mkdocs-section-index",
    "mkdocs-material",
    "markdown-include",
]

[tool.bumpver]
current_version = "2024.1003"
version_pattern = "YYYY.BUILD"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = false

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'version = "{version}"',
]
