[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "bag3d-common"
version = "2024.1004"
description = "Resources, functions and type definitions that are used by the 3D BAG packages that define the data processing workflows."
readme = "README.md"
requires-python = ">=3.11"
authors = [
    { name = "Balázs Dukai", email = "balazs.dukai@3dgi.nl" },
    { name = "Ravi Peters", email = "ravi.peters@3dgi.nl" },
    { name = "Gina Stavropoulou", email = "G.Stavropoulou@tudelft.nl" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: GIS",
    "License :: OSI Approved :: Apache Software License"
]
urls = { github = "https://github.com/3DBAG/3dbag-pipeline" }
dependencies = [
    "dagster-shell>=0.25.3",
    "dagster>=1.9.3",
    "certifi>=2024.8.30",
    "docker>=7.1.0",
    "requests>=2.32.3",
    "pgutils",
    "psycopg[binary]>=3.2.3",
]

[project.optional-dependencies]
dev = [
    "coverage>=7.6.9",
    "pytest>=8.3.4",
    "pytest-dotenv>=0.5.2",
]

[tool.ruff]
line-length = 88

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = false

[tool.uv.sources]
pgutils = { git = "https://github.com/balazsdukai/pgutils.git", rev = "2024.1013" }
