#!/bin/bash

version=$(python3 -c "import json; print(json.load(open('3dbag-manifest.json'))['version'])")
if ! grep -q "\[${version}\]" CHANGELOG.md; then
    echo "Error: CHANGELOG.md has not been updated for version ${version}"
    exit 1
fi
