[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "bag3d-core"
version = "2022.1003"
description = "Workflow for producing the 3D BAG core data set"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "Propietary" }
authors = [
    { name = "3DGI", email = "info@3dgi.nl" },
    { name = "Gina Stavropoulou", email = "G.Stavropoulou@tudelft.nl" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: GIS",
    "License :: Other/Proprietary License"
]
urls = { github = "https://github.com/3DGI/3dbag-pipeline" }
dependencies = [
    "bag3d-common",
    "dagster",
    "dagster-postgres",
    "dagster-shell",
    "docker",
    "pgutils @ git+https://github.com/balazsdukai/pgutils.git@2022.1011#egg=pgutils",
    "psycopg[binary]",
    "lxml>=4.6",
    "fabric"
]
optional-dependencies = { dev = ["pytest", "bumpver", "tox", "dagster-webserver"] }

[tool.bumpver]
current_version = "2022.1003"
version_pattern = "YYYY.BUILD"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = false

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'version = "{version}"',
]

