[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "bag3d-core"
version = "2024.1006"
description = "Workflow for producing the 3D BAG core data set"
readme = "README.md"
requires-python = ">=3.11"
authors = [
    { name = "Balázs Dukai", email = "balazs.dukai@3dgi.nl" },
    { name = "Ravi Peters", email = "ravi.peters@3dgi.nl" },
    { name = "Gina Stavropoulou", email = "G.Stavropoulou@tudelft.nl" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: GIS",
    "License :: OSI Approved :: Apache Software License"
]
urls = { github = "https://github.com/3DBAG/3dbag-pipeline" }
dependencies = [
    "pgutils",
    "bag3d-common",
    "psycopg[binary]>=3.2.3",
    "dagster>=1.9.4",
    "dagster-postgres>=0.25.4",
    "dagster-shell>=0.25.4",
    "docker>=7.1.0",
    "fabric>=3.2.2",
    "lxml>=5.3.0",
]

[project.optional-dependencies] 
dev = [
    "coverage>=7.6.8",
    "pytest>=8.3.4",
    "pytest-dotenv>=0.5.2",
    "ruff>=0.8.1",
]
docs = [
    "markdown-include>=0.8.1",
    "mkdocs-material>=9.5.48",
    "mkdocs>=1.6.1",
    "mkdocs-gen-files>=0.5.0",
    "mkdocs-literate-nav>=0.6.1",
    "mkdocs-section-index>=0.3.9",
]


[tool.ruff]
line-length = 88

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = false


[tool.uv.sources]
bag3d-common = { path = "../common"}
pgutils = { git = "https://github.com/balazsdukai/pgutils.git", rev = "2024.1013" }
