[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "bag3d-core"
version = "2024.1006"
description = "Workflow for producing the 3D BAG core data set"
readme = "README.md"
requires-python = ">=3.8"
authors = [
    { name = "Balázs Dukai", email = "balazs.dukai@3dgi.nl" },
    { name = "Ravi Peters", email = "ravi.peters@3dgi.nl" },
    { name = "Gina Stavropoulou", email = "G.Stavropoulou@tudelft.nl" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: GIS",
    "License :: OSI Approved :: Apache Software License"
]
urls = { github = "https://github.com/3DBAG/3dbag-pipeline" }
dependencies = [
    "bag3d-common @ git+https://github.com/3DBAG/3dbag-pipeline.git@FileStoreResource#egg=bag3d-common&subdirectory=packages/common",
    "dagster",
    "dagster-postgres",
    "dagster-shell",
    "docker",
    "pgutils @ git+https://github.com/balazsdukai/pgutils.git@2024.1013#egg=pgutils",
    "psycopg[binary]",
    "lxml>=4.6",
    "fabric"
]
optional-dependencies = { dev = ["pytest", "bumpver", "tox", "dagster-webserver", "pytest-dotenv", "coverage", "ruff"] }

[tool.bumpver]
current_version = "2024.1006"
version_pattern = "YYYY.BUILD"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = false

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'version = "{version}"',
]

[tool.ruff]
line-length = 88

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = false