name: Build and Publish Docker Images

on:
  push:
    tags:
      - '202[2-9].[0-9]+.[0-9]+'
      - '202[2-9].[0-9]+-pc[0-9]+'
  pull_request:
    branches:
      - "develop"
    types: [ closed ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set docker image tag to 'develop'
        if: github.ref == 'refs/heads/develop'
        run: echo "DOCKER_TAG=develop" >> $GITHUB_ENV
      - name: Set docker image tag to git tag
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "DOCKER_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push core
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./docker/pipeline/bag3d-core.dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            JOBS=2
            VERSION=${{ env.DOCKER_TAG }}
          push: true
          tags: 3dgi/3dbag-pipeline-core:${{ env.DOCKER_TAG }}
      - name: Build and push floors estimation
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./docker/pipeline/bag3d-floors-estimation.dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            JOBS=2
            VERSION=${{ env.DOCKER_TAG }}
          push: true
          tags: 3dgi/3dbag-pipeline-floors-estimation:${{ env.DOCKER_TAG }}
      - name: Build and push party walls
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./docker/pipeline/bag3d-party-walls.dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            JOBS=2
            VERSION=${{ env.DOCKER_TAG }}
          push: true
          tags: 3dgi/3dbag-pipeline-party-walls:${{ env.DOCKER_TAG }}
      - name: Build and push dagster
        uses: docker/build-push-action@v6
        with:
          context: ./docker/dagster
          file: ./docker/dagster/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            JOBS=2
            VERSION=${{ env.DOCKER_TAG }}
          push: true
          tags: 3dgi/3dbag-pipeline-dagster:${{ env.DOCKER_TAG }}
