name: Build and Publish Docker Images

on:
  pull_request:
    branches:
      - develop
    types: [closed]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push core
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./docker/pipeline/bag3d-core.dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            JOBS=2
            VERSION=develop
          push: true
          tags: 3dgi/3dbag-pipeline-core:develop
      - name: Build and push floors estimation
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./docker/pipeline/bag3d-floors-estimation.dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            JOBS=2
            VERSION=develop
          push: true
          tags: 3dgi/3dbag-pipeline-floors-estimation:develop
      - name: Build and push party walls
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./docker/pipeline/bag3d-party-walls.dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            JOBS=2
            VERSION=develop
          push: true
          tags: 3dgi/3dbag-pipeline-party-walls:develop
      - name: Build and push dagster
        uses: docker/build-push-action@v6
        with:
          context: ./docker/dagster
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            JOBS=2
            VERSION=develop
          push: true
          tags: 3dgi/3dbag-pipeline-dagster:develop
